name: Trigger auto deployment for nvss-canary-staging

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/nvss-canary-staging-AutoDeployTrigger-1c1ea27d-525a-468e-b4c7-11a445944975.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NVSSCANARYSTAGING_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ctenvss20221223092705.azurecr.io
          registryUsername: ${{ secrets.NVSSCANARYSTAGING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NVSSCANARYSTAGING_REGISTRY_PASSWORD }}
          containerAppName: nvss-canary-staging
          resourceGroup: CTE_NVSS
          imageToBuild: ctenvss20221223092705.azurecr.io/nvss-canary-staging:${{ github.sha }}
          

     

